"""Turn on email alerts for the monitoring stack (one-time, local only).

    python scripts/setup_alert_email.py
    docker compose up -d alertmanager prometheus
    make test-alert          # you should get an email within ~1 minute

Writes (all git-ignored, never commit them):
  monitoring/alertmanager/alertmanager.local.yml
  monitoring/alertmanager/secrets/smtp_password
  .env                      (ALERTMANAGER_CONFIG=alertmanager.local.yml)

For Gmail: create an App Password (Google Account > Security > 2-Step
Verification > App passwords) and use it instead of your normal password.
"""

from __future__ import annotations

import argparse
import getpass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AM_DIR = ROOT / "monitoring" / "alertmanager"

TEMPLATE = """# Generated by scripts/setup_alert_email.py. Do not commit (contains your address).
route:
  receiver: email
  group_by: [alertname, finding]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: email
    email_configs:
      - to: {to}
        from: {sender}
        smarthost: {smarthost}
        auth_username: {username}
        auth_password_file: /etc/alertmanager/secrets/smtp_password
        require_tls: true
        send_resolved: true

inhibit_rules:
  - source_matchers: [alertname="ChexpertApiDown"]
    target_matchers: [alertname=~"ChexpertHighErrorRate|ChexpertSlowPredictions|ChexpertPredictionDrift"]
"""


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--to")
    ap.add_argument("--sender", help="From address (default: same as --to)")
    ap.add_argument("--username", help="SMTP login (default: --sender)")
    ap.add_argument("--smarthost", default="smtp.gmail.com:587")
    ap.add_argument("--password", help="SMTP/app password (prompted if omitted)")
    args = ap.parse_args(argv)

    to = args.to or input("Send alerts to (email): ").strip()
    sender = args.sender or to
    username = args.username or sender
    password = args.password or getpass.getpass("SMTP / Gmail app password: ")

    (AM_DIR / "secrets").mkdir(parents=True, exist_ok=True)
    secret = AM_DIR / "secrets" / "smtp_password"
    secret.write_text(password)
    secret.chmod(0o644)  # the alertmanager container runs as 'nobody' and must read it
    (AM_DIR / "alertmanager.local.yml").write_text(
        TEMPLATE.format(to=to, sender=sender, username=username, smarthost=args.smarthost))

    env = ROOT / ".env"
    lines = [ln for ln in (env.read_text().splitlines() if env.exists() else [])
             if not ln.startswith("ALERTMANAGER_CONFIG=")]
    env.write_text("\n".join([*lines, "ALERTMANAGER_CONFIG=alertmanager.local.yml"]) + "\n")
    print(f"Email alerts configured for {to}. Restart: docker compose up -d alertmanager")


if __name__ == "__main__":
    main()
